// <auto-generated />
using System;
using HRInfoAdvertisements.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRInfoAdvertisements.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Advertisement", b =>
                {
                    b.Property<long>("AdvertisementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdvertisementID"));

                    b.Property<string>("AddressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdvertisementNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AdvertisementTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("AreaID")
                        .HasColumnType("int");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<decimal?>("BuiltUpArea")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("BHD");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FeaturedUntil")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNegotiable")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LandArea")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlotNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int?>("PropertyAge")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StateID")
                        .HasColumnType("int");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TitleAr")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("AdvertisementID");

                    b.HasIndex("AdvertisementNumber")
                        .IsUnique();

                    b.HasIndex("AdvertisementTypeID");

                    b.HasIndex("AreaID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CityID");

                    b.HasIndex("CountryID");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("Price");

                    b.HasIndex("PublishedDate");

                    b.HasIndex("StateID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UserID");

                    b.ToTable("Advertisements", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CategoryNameAr")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("AdvertisementCategories", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementDocument", b =>
                {
                    b.Property<long>("AdvertisementDocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdvertisementDocumentID"));

                    b.Property<long>("AdvertisementID")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileURL")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("AdvertisementDocumentID");

                    b.HasIndex("AdvertisementID");

                    b.ToTable("AdvertisementDocuments", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementEnquiry", b =>
                {
                    b.Property<long>("AdvertisementEnquiryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdvertisementEnquiryID"));

                    b.Property<long>("AdvertisementID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactMobile")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastRepliedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<long>("RecipientUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("SenderUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdvertisementEnquiryID");

                    b.HasIndex("RecipientUserID");

                    b.HasIndex("SenderUserID");

                    b.HasIndex("AdvertisementID", "CreatedDate");

                    b.ToTable("AdvertisementEnquiries", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementEnquiryMessage", b =>
                {
                    b.Property<long>("AdvertisementEnquiryMessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdvertisementEnquiryMessageID"));

                    b.Property<long>("AdvertisementEnquiryID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SenderUserID")
                        .HasColumnType("bigint");

                    b.HasKey("AdvertisementEnquiryMessageID");

                    b.HasIndex("AdvertisementEnquiryID", "CreatedDate");

                    b.HasIndex("SenderUserID", "IsRead");

                    b.ToTable("AdvertisementEnquiryMessages", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementFavorite", b =>
                {
                    b.Property<long>("AdvertisementFavoriteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdvertisementFavoriteID"));

                    b.Property<long>("AdvertisementID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("AdvertisementFavoriteID");

                    b.HasIndex("AdvertisementID");

                    b.HasIndex("UserID", "AdvertisementID")
                        .IsUnique();

                    b.ToTable("AdvertisementFavorites", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementFeature", b =>
                {
                    b.Property<int>("AdvertisementFeatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdvertisementFeatureID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FeatureNameAr")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.HasKey("AdvertisementFeatureID");

                    b.HasIndex("CategoryID");

                    b.ToTable("AdvertisementFeatures", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementFeatureValue", b =>
                {
                    b.Property<long>("AdvertisementFeatureValueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdvertisementFeatureValueID"));

                    b.Property<int>("AdvertisementFeatureID")
                        .HasColumnType("int");

                    b.Property<long>("AdvertisementID")
                        .HasColumnType("bigint");

                    b.Property<string>("FeatureValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FeatureValueAr")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("AdvertisementFeatureValueID");

                    b.HasIndex("AdvertisementFeatureID");

                    b.HasIndex("AdvertisementID", "AdvertisementFeatureID")
                        .IsUnique();

                    b.ToTable("AdvertisementFeatureValues", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementImage", b =>
                {
                    b.Property<long>("AdvertisementImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdvertisementImageID"));

                    b.Property<long>("AdvertisementID")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileURL")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("AdvertisementImageID");

                    b.HasIndex("AdvertisementID", "DisplayOrder");

                    b.ToTable("AdvertisementImages", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublicStatus")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusNameAr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusCode")
                        .IsUnique();

                    b.ToTable("AdvertisementStatuses", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementType", b =>
                {
                    b.Property<int>("AdvertisementTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdvertisementTypeID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TypeNameAr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdvertisementTypeID");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("AdvertisementTypes", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementVideo", b =>
                {
                    b.Property<long>("AdvertisementVideoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdvertisementVideoID"));

                    b.Property<long>("AdvertisementID")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileURL")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("AdvertisementVideoID");

                    b.HasIndex("AdvertisementID");

                    b.ToTable("AdvertisementVideos", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementView", b =>
                {
                    b.Property<long>("AdvertisementViewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdvertisementViewID"));

                    b.Property<long>("AdvertisementID")
                        .HasColumnType("bigint");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ViewedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AdvertisementViewID");

                    b.HasIndex("UserID");

                    b.HasIndex("AdvertisementID", "ViewedDate");

                    b.ToTable("AdvertisementViews", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.ApprovalHistory", b =>
                {
                    b.Property<long>("ApprovalHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ApprovalHistoryID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ActionedByUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("ApprovalRequestID")
                        .HasColumnType("bigint");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("ApprovalHistoryID");

                    b.HasIndex("ActionedByUserID");

                    b.HasIndex("ApprovalRequestID");

                    b.ToTable("ApprovalHistories", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Property<long>("ApprovalRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ApprovalRequestID"));

                    b.Property<long>("AdvertisementID")
                        .HasColumnType("bigint");

                    b.Property<long?>("AssignedToUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("SubmittedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ApprovalRequestID");

                    b.HasIndex("AdvertisementID");

                    b.HasIndex("AssignedToUserID");

                    b.HasIndex("SubmittedByUserID");

                    b.HasIndex("Status", "SubmittedDate");

                    b.ToTable("ApprovalRequests", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Area", b =>
                {
                    b.Property<int>("AreaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaID"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AreaNameAr")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("StateID")
                        .HasColumnType("int");

                    b.HasKey("AreaID");

                    b.HasIndex("CityID");

                    b.HasIndex("StateID");

                    b.HasIndex("CountryID", "StateID", "CityID", "AreaName")
                        .IsUnique()
                        .HasFilter("[StateID] IS NOT NULL AND [CityID] IS NOT NULL");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("AuditLogID");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("UserID");

                    b.HasIndex("EntityName", "EntityID");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityID"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CityNameAr")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("StateID")
                        .HasColumnType("int");

                    b.HasKey("CityID");

                    b.HasIndex("StateID");

                    b.HasIndex("CountryID", "StateID", "CityName")
                        .IsUnique()
                        .HasFilter("[StateID] IS NOT NULL");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryID"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CountryNameAr")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CountryID");

                    b.HasIndex("CountryCode")
                        .IsUnique();

                    b.HasIndex("CountryName")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Favorite", b =>
                {
                    b.Property<long>("FavoriteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FavoriteID"));

                    b.Property<long>("AdvertisementID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("FavoriteID");

                    b.HasIndex("AdvertisementID");

                    b.HasIndex("UserID", "AdvertisementID")
                        .IsUnique();

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Location", b =>
                {
                    b.Property<long>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LocationID"));

                    b.Property<string>("AddressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationNameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.HasKey("LocationID");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.LoginHistory", b =>
                {
                    b.Property<long>("LoginHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LoginHistoryID"));

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("LoginHistoryID");

                    b.HasIndex("LoginDate");

                    b.HasIndex("UserID");

                    b.ToTable("LoginHistories", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Message", b =>
                {
                    b.Property<long>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageID"));

                    b.Property<long?>("AdvertisementID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("EnquiryID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ReceiverUserID")
                        .HasColumnType("bigint");

                    b.Property<long>("SenderUserID")
                        .HasColumnType("bigint");

                    b.HasKey("MessageID");

                    b.HasIndex("AdvertisementID");

                    b.HasIndex("EnquiryID");

                    b.HasIndex("SenderUserID");

                    b.HasIndex("ReceiverUserID", "IsRead", "CreatedDate");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("NotificationTemplateID")
                        .HasColumnType("int");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ReferenceID")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("NotificationID");

                    b.HasIndex("NotificationTemplateID");

                    b.HasIndex("UserID", "IsRead", "CreatedDate");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<int>("NotificationTemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationTemplateID"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPushEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSmsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("NotificationTemplateID");

                    b.HasIndex("TemplateCode")
                        .IsUnique();

                    b.ToTable("NotificationTemplates", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.OTPRequest", b =>
                {
                    b.Property<long>("OTPRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OTPRequestID"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConsumedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("bit");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("OTPHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("OTPRequestID");

                    b.HasIndex("UserID");

                    b.HasIndex("Destination", "Purpose", "CreatedDate");

                    b.ToTable("OTPRequests", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PermissionID");

                    b.HasIndex("PermissionCode")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("RefreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RefreshTokenID"));

                    b.Property<string>("CreatedByIPAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIPAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("RefreshTokenID");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserID", "ExpiresAt");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.RejectionReason", b =>
                {
                    b.Property<int>("RejectionReasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RejectionReasonID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonTextAr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RejectionReasonID");

                    b.ToTable("RejectionReasons");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Report", b =>
                {
                    b.Property<long>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportID"));

                    b.Property<long>("AdvertisementID")
                        .HasColumnType("bigint");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReportReasonID")
                        .HasColumnType("int");

                    b.Property<long>("ReportedByUserID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReviewedByUserID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ReportID");

                    b.HasIndex("AdvertisementID");

                    b.HasIndex("ReportReasonID");

                    b.HasIndex("ReportedByUserID");

                    b.HasIndex("ReviewedByUserID");

                    b.HasIndex("Status", "CreatedDate");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.ReportReason", b =>
                {
                    b.Property<int>("ReportReasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportReasonID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReasonText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ReasonTextAr")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ReportReasonID");

                    b.HasIndex("ReasonCode")
                        .IsUnique();

                    b.ToTable("ReportReasons", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.RolePermission", b =>
                {
                    b.Property<long>("RolePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RolePermissionID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermissionID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionID");

                    b.HasIndex("PermissionID");

                    b.HasIndex("RoleID", "PermissionID")
                        .IsUnique();

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.SavedSearch", b =>
                {
                    b.Property<long>("SavedSearchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SavedSearchID"));

                    b.Property<long?>("AdvertisementID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EnableNotifications")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SearchCriteriaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("SavedSearchID");

                    b.HasIndex("AdvertisementID");

                    b.HasIndex("UserID");

                    b.ToTable("SavedSearches", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.State", b =>
                {
                    b.Property<int>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateID"));

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("StateNameAr")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("StateID");

                    b.HasIndex("CountryID", "StateName")
                        .IsUnique();

                    b.ToTable("States", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("SystemSettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemSettingID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SettingValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("SystemSettingID");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserID"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMFAEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMobileVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MobileNo")
                        .IsUnique()
                        .HasFilter("[MobileNo] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.UserAddress", b =>
                {
                    b.Property<long>("UserAddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserAddressID"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("AreaID")
                        .HasColumnType("int");

                    b.Property<string>("BlockNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BuildingNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RoadNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StateID")
                        .HasColumnType("int");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("UserAddressID");

                    b.HasIndex("AreaID");

                    b.HasIndex("CityID");

                    b.HasIndex("CountryID");

                    b.HasIndex("StateID");

                    b.HasIndex("UserID");

                    b.ToTable("UserAddresses", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.UserProfile", b =>
                {
                    b.Property<long>("UserProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserProfileID"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsBusinessAccount")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("en");

                    b.Property<string>("ProfilePhotoURL")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("UserProfileID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserRoleID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("UserRoleID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID", "RoleID")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.UserSession", b =>
                {
                    b.Property<long>("UserSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserSessionID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("UserSessionID");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Advertisement", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.AdvertisementType", "AdvertisementType")
                        .WithMany("Advertisements")
                        .HasForeignKey("AdvertisementTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Area", "Area")
                        .WithMany("Advertisements")
                        .HasForeignKey("AreaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.AdvertisementCategory", "Category")
                        .WithMany("Advertisements")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.City", "City")
                        .WithMany("Advertisements")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Country", "Country")
                        .WithMany("Advertisements")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.State", "State")
                        .WithMany("Advertisements")
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.AdvertisementStatus", "Status")
                        .WithMany("Advertisements")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "User")
                        .WithMany("Advertisements")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdvertisementType");

                    b.Navigation("Area");

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("State");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementDocument", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Advertisement", "Advertisement")
                        .WithMany("Documents")
                        .HasForeignKey("AdvertisementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementEnquiry", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Advertisement", "Advertisement")
                        .WithMany("Enquiries")
                        .HasForeignKey("AdvertisementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("RecipientUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementEnquiryMessage", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.AdvertisementEnquiry", "AdvertisementEnquiry")
                        .WithMany("Messages")
                        .HasForeignKey("AdvertisementEnquiryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdvertisementEnquiry");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementFavorite", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Advertisement", "Advertisement")
                        .WithMany()
                        .HasForeignKey("AdvertisementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementFeature", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.AdvertisementCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementFeatureValue", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.AdvertisementFeature", "Feature")
                        .WithMany("Values")
                        .HasForeignKey("AdvertisementFeatureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Advertisement", "Advertisement")
                        .WithMany("FeatureValues")
                        .HasForeignKey("AdvertisementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementImage", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Advertisement", "Advertisement")
                        .WithMany("Images")
                        .HasForeignKey("AdvertisementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementVideo", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Advertisement", "Advertisement")
                        .WithMany("Videos")
                        .HasForeignKey("AdvertisementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementView", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Advertisement", "Advertisement")
                        .WithMany("Views")
                        .HasForeignKey("AdvertisementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Advertisement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.ApprovalHistory", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "ActionedByUser")
                        .WithMany()
                        .HasForeignKey("ActionedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.ApprovalRequest", "ApprovalRequest")
                        .WithMany("ApprovalHistory")
                        .HasForeignKey("ApprovalRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionedByUser");

                    b.Navigation("ApprovalRequest");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.ApprovalRequest", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Advertisement", "Advertisement")
                        .WithMany("ApprovalRequests")
                        .HasForeignKey("AdvertisementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("AssignedToUser");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Area", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.City", "City")
                        .WithMany("Areas")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Country", "Country")
                        .WithMany("Areas")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.State", "State")
                        .WithMany("Areas")
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.City", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");

                    b.Navigation("State");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Advertisement", "Advertisement")
                        .WithMany("Favorites")
                        .HasForeignKey("AdvertisementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.LoginHistory", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Message", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Advertisement", "Advertisement")
                        .WithMany("Messages")
                        .HasForeignKey("AdvertisementID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.AdvertisementEnquiry", "Enquiry")
                        .WithMany()
                        .HasForeignKey("EnquiryID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "ReceiverUser")
                        .WithMany()
                        .HasForeignKey("ReceiverUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Advertisement");

                    b.Navigation("Enquiry");

                    b.Navigation("ReceiverUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Notification", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.NotificationTemplate", "NotificationTemplate")
                        .WithMany()
                        .HasForeignKey("NotificationTemplateID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationTemplate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.OTPRequest", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Report", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Advertisement", "Advertisement")
                        .WithMany("Reports")
                        .HasForeignKey("AdvertisementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.ReportReason", "ReportReason")
                        .WithMany("Reports")
                        .HasForeignKey("ReportReasonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Advertisement");

                    b.Navigation("ReportReason");

                    b.Navigation("ReportedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.SavedSearch", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Advertisement", null)
                        .WithMany("SavedSearches")
                        .HasForeignKey("AdvertisementID");

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.State", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.UserAddress", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("State");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("HRInfoAdvertisements.Domain.Entities.UserProfile", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("HRInfoAdvertisements.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Advertisement", b =>
                {
                    b.Navigation("ApprovalRequests");

                    b.Navigation("Documents");

                    b.Navigation("Enquiries");

                    b.Navigation("Favorites");

                    b.Navigation("FeatureValues");

                    b.Navigation("Images");

                    b.Navigation("Messages");

                    b.Navigation("Reports");

                    b.Navigation("SavedSearches");

                    b.Navigation("Videos");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementCategory", b =>
                {
                    b.Navigation("Advertisements");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementEnquiry", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementFeature", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementStatus", b =>
                {
                    b.Navigation("Advertisements");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.AdvertisementType", b =>
                {
                    b.Navigation("Advertisements");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.ApprovalRequest", b =>
                {
                    b.Navigation("ApprovalHistory");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Area", b =>
                {
                    b.Navigation("Advertisements");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.City", b =>
                {
                    b.Navigation("Advertisements");

                    b.Navigation("Areas");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Country", b =>
                {
                    b.Navigation("Advertisements");

                    b.Navigation("Areas");

                    b.Navigation("Cities");

                    b.Navigation("States");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.ReportReason", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.State", b =>
                {
                    b.Navigation("Advertisements");

                    b.Navigation("Areas");

                    b.Navigation("Cities");
                });

            modelBuilder.Entity("HRInfoAdvertisements.Domain.Entities.User", b =>
                {
                    b.Navigation("Advertisements");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserAddresses");

                    b.Navigation("UserProfile");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
